/-
Pythia.GaussianRandomWalk — crossing-probability scaffold
for sub-Gaussian random walks.

Downstream of `Pythia.GaussianSmallBall`:
the `gaussian_small_ball_lower_bound` lemma gives the per-step
anti-concentration that supports a boundary-hugging Gaussian-walk
adversary.  Here we build the random-walk object itself: a sum of
iid standard Gaussian increments on `ℝ^ℕ` with the canonical product
measure and canonical filtration.

Target lemmas:

* `gaussianProductMeasure` (closed): `Measure.infinitePiNat` over
  per-coordinate `gaussianReal 0 σ²`. From Aristotle project
  `9156a0fd` (2026-04-28), partial closure.
* `IsFiniteMeasure (gaussianProductMeasure σ)` instance (closed):
  inferred from `Measure.infinitePiNat`'s automatic instance.
* `canonicalFiltration` (closed): `iSup`-of-comap construction,
  generated by the first `n` coordinate projections (indices `0,…,n−1`).
* `gaussianWalk_isSubGaussianMG` (closed): the
  iid-Gaussian random walk `M_t = Σ_{i<t} ω_i` realises the Pythia
  `SubGaussianMG` structure with parameter σ, with the structure's
  process field pinned to `gaussianWalk` (no degenerate constant
  / zero-process witnesses can inhabit this type).

The proof factors through `Pythia.one_d_marginal_reduction_tight`
(in `Pythia.VectorSharpness`), which turns five hypotheses on a
process M into `∃ M' : SubGaussianMG σ 𝓕 μ, M'.process = M`. Each
of the five sub-targets below is a named lemma, all now closed.
-/

import Mathlib
import Pythia.Basic
import Pythia.GaussianSmallBall
import Pythia.SubGaussianMG
import Pythia.VectorSharpness

namespace Pythia

open MeasureTheory ProbabilityTheory

/-- The canonical MeasurableSpace on `ℕ → ℝ`: the product sigma-
algebra from the per-coordinate Borel sigma-algebra on `ℝ`. Named
for downstream reuse in `canonicalFiltration` + `gaussianWalk`. -/
instance canonicalMeasurableSpace : MeasurableSpace (ℕ → ℝ) :=
  MeasurableSpace.pi

/-- The product measure `μ_ℝℕ = ⨂_{n ∈ ℕ} gaussianReal 0 σ²` on
`ℝ^ℕ`: the canonical iid-standard-Gaussian-increment space. -/
noncomputable def gaussianProductMeasure (σ : ℝ) :
    @Measure (ℕ → ℝ) canonicalMeasurableSpace :=
  Measure.infinitePiNat (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2)))

/-- The Gaussian product measure is a finite measure (in fact a
probability measure). -/
noncomputable instance (σ : ℝ) :
    IsFiniteMeasure (gaussianProductMeasure σ) := by
  unfold gaussianProductMeasure
  exact inferInstanceAs (IsFiniteMeasure (Measure.infinitePiNat _))

/-- The canonical filtration on `ℝ^ℕ`: `𝓕_n` is the σ-algebra
generated by the first `n` coordinate projections `ω₀, …, ω_{n−1}`.
Adapted processes are those whose `t`-th value depends only on the
first `t` increments (coordinates `0, …, t−1`). The use of `j < n`
(rather than `j ≤ n`) ensures the increment `ω_t` at step `t` is
*not* `𝓕_t`-measurable, which is necessary for the conditional
sub-Gaussian MGF bound in `gaussianWalk_increments_subG`. -/
noncomputable def canonicalFiltration :
    Filtration ℕ canonicalMeasurableSpace where
  seq n := ⨆ (j : ℕ) (_ : j < n),
    MeasurableSpace.comap (fun (ω : ℕ → ℝ) => ω j) (borel ℝ)
  mono' i j hij :=
    iSup_mono fun k => iSup_mono' fun hk => ⟨lt_of_lt_of_le hk hij, le_rfl⟩
  le' n := iSup_le fun j => iSup_le fun _ => (measurable_pi_apply j).comap_le

/-- The Gaussian random walk: `M_t ω = Σ_{i < t} ω i`.  On the
canonical-filtration / gaussian-product measure space this is a
`SubGaussianMG` instance. -/
noncomputable def gaussianWalk (t : ℕ) (ω : ℕ → ℝ) : ℝ :=
  (Finset.range t).sum (fun i => ω i)

/-! ## Helpers: product-measure ↔ `infinitePi` bridge + independence -/

/-- `gaussianProductMeasure σ` equals `Measure.infinitePi` applied to the
same per-coordinate Gaussian, which unlocks `iIndepFun_infinitePi`. -/
lemma gaussianProductMeasure_eq_infinitePi (σ : ℝ) :
    gaussianProductMeasure σ =
      Measure.infinitePi (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2))) := by
  apply @Measure.eq_infinitePi ℕ (fun _ => ℝ) _ _ _
  intro s t ht
  have hrestr := Measure.infinitePiNat_map_restrict
    (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2))) s
  have key : (s : Set ℕ).pi t =
      s.restrict ⁻¹' (Set.pi Set.univ (fun (i : s) => t ↑i)) := by ext x; simp [Finset.restrict]
  rw [key, ← Measure.map_apply (Finset.measurable_restrict s)
    (MeasurableSet.univ_pi (fun (i : s) => ht ↑i))]
  unfold gaussianProductMeasure
  rw [hrestr, Measure.pi_pi]
  exact Finset.prod_attach s (fun i => (gaussianReal 0 (Real.toNNReal (σ ^ 2))) (t i))

/-- The coordinate projections are `iIndepFun` under `gaussianProductMeasure`. -/
lemma gaussianProductMeasure_iIndepFun (σ : ℝ) :
    iIndepFun (m := fun _ => borel ℝ)
      (fun (i : ℕ) (ω : ℕ → ℝ) => ω i) (gaussianProductMeasure σ) := by
  rw [gaussianProductMeasure_eq_infinitePi]
  exact iIndepFun_infinitePi (fun _ => measurable_id)

/-
The marginal of coordinate `i` under `gaussianProductMeasure σ` is
`gaussianReal 0 (Real.toNNReal (σ^2))`.
-/
lemma gaussianProductMeasure_map_coord (σ : ℝ) (i : ℕ) :
    (gaussianProductMeasure σ).map (fun ω : ℕ → ℝ => ω i) =
      gaussianReal 0 (Real.toNNReal (σ ^ 2)) := by
  ext s hs;
  rw [ Measure.map_apply ] <;> norm_num [ hs ];
  · -- By definition of `gaussianProductMeasure`, we know that it is the product of Gaussian measures.
    have h_prod : gaussianProductMeasure σ = Measure.infinitePi (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2))) :=
      gaussianProductMeasure_eq_infinitePi σ;
    have := @Measure.infinitePi_pi;
    convert @this ℕ ( fun _ => ℝ ) ( fun _ => borel ℝ ) ( fun _ => gaussianReal 0 ( Real.toNNReal ( σ ^ 2 ) ) ) _ { i } ( fun _ => s ) _ using 1 <;> norm_num [ h_prod ];
    exact hs;
  · exact measurable_pi_apply i

/-- Each coordinate projection is integrable under `gaussianProductMeasure`. -/
lemma coord_integrable (σ : ℝ) (i : ℕ) :
    Integrable (fun ω : ℕ → ℝ => ω i) (gaussianProductMeasure σ) := by
  have hmarg := gaussianProductMeasure_map_coord σ i
  have : Integrable id (Measure.map (fun ω : ℕ → ℝ => ω i) (gaussianProductMeasure σ)) := by
    rw [hmarg]; exact IsGaussian.integrable_id
  exact (integrable_map_measure measurable_id.aestronglyMeasurable
    (measurable_pi_apply i).aemeasurable).mp this

/-- Each `exp(lam * ω i)` is integrable under `gaussianProductMeasure`. -/
lemma coord_integrable_exp (σ : ℝ) (i : ℕ) (lam : ℝ) :
    Integrable (fun ω : ℕ → ℝ => Real.exp (lam * ω i))
      (gaussianProductMeasure σ) := by
  have hmarg := gaussianProductMeasure_map_coord σ i
  have key : Integrable (fun x => Real.exp (lam * x))
      (Measure.map (fun ω : ℕ → ℝ => ω i) (gaussianProductMeasure σ)) := by
    rw [hmarg]; exact integrable_exp_mul_gaussianReal lam
  have := key.comp_measurable (measurable_pi_apply i)
  convert this using 1

/-- The increment `gaussianWalk (t+1) - gaussianWalk t` simplifies to `ω t`. -/
lemma gaussianWalk_increment (t : ℕ) (ω : ℕ → ℝ) :
    gaussianWalk (t + 1) ω - gaussianWalk t ω = ω t := by
  simp [gaussianWalk, Finset.sum_range_succ]

/-
The `t`-th coordinate generates a sigma-algebra independent of
`canonicalFiltration t` under `gaussianProductMeasure σ`. This is the
key fact: under the iid product measure, `ω_t` is independent of
`σ(ω₀, …, ω_{t−1})`.
-/
lemma coord_indep_filtration (σ : ℝ) (t : ℕ) :
    Indep (MeasurableSpace.comap (fun ω : ℕ → ℝ => ω t) (borel ℝ))
      (canonicalFiltration t)
      (gaussianProductMeasure σ) := by
  have := @gaussianProductMeasure_iIndepFun σ;
  -- Apply the independence result to the sets {t} and {j | j < t}.
  have h_indep : Indep (⨆ i ∈ ({t} : Set ℕ), MeasurableSpace.comap (fun ω => ω i) (borel ℝ)) (⨆ i ∈ {j | j < t}, MeasurableSpace.comap (fun ω => ω i) (borel ℝ)) (gaussianProductMeasure σ) := by
    apply_rules [ indep_iSup_of_disjoint ];
    · exact fun i => ( measurable_pi_apply i ).comap_le;
    · aesop;
  simp_all +decide [ canonicalFiltration ]

/-
The integral of the `t`-th coordinate under `gaussianProductMeasure σ`
is zero (the mean of `gaussianReal 0 σ²`).
-/
lemma coord_integral_zero (σ : ℝ) (t : ℕ) :
    ∫ ω : ℕ → ℝ, ω t ∂gaussianProductMeasure σ = 0 := by
  have h_zero_mean : ∫ ω : ℕ → ℝ, ω t ∂gaussianProductMeasure σ = ∫ x : ℝ, x ∂(gaussianProductMeasure σ).map (fun ω => ω t) := by
    rw [ MeasureTheory.integral_map ];
    · exact measurable_pi_apply t |> Measurable.aemeasurable;
    · exact measurable_id.aestronglyMeasurable;
  convert h_zero_mean using 1;
  rw [ gaussianProductMeasure_map_coord ];
  exact (integral_id_gaussianReal).symm

/-! ## SubGaussianMG hypothesis-helpers for `gaussianWalk` -/

/-- Hypothesis 1: the gaussian random walk is adapted to
`canonicalFiltration`. `gaussianWalk t = Σ_{i<t} ω_i` depends only
on the first `t` coordinates, all of which are
`canonicalFiltration t`-measurable by construction (the filtration
is the σ-algebra generated by coordinates `j < t`). -/
lemma gaussianWalk_adapted :
    Adapted canonicalFiltration gaussianWalk := by
  intro t
  exact Finset.measurable_sum _ fun i hi =>
    Measurable.of_comap_le (le_iSup₂_of_le i (Finset.mem_range.mp hi) le_rfl)

/-- Hypothesis 2: each `gaussianWalk t` is integrable under the
Gaussian product measure. -/
lemma gaussianWalk_integrable (σ : ℝ) :
    ∀ t, Integrable (gaussianWalk t) (gaussianProductMeasure σ) := by
  intro t
  exact integrable_finset_sum _ fun i _ => coord_integrable σ i

/-
Hypothesis 3: each `Real.exp (lam * gaussianWalk t)` is
integrable for every `lam : ℝ`.
-/
lemma gaussianWalk_integrable_exp (σ : ℝ) :
    ∀ t : ℕ, ∀ lam : ℝ,
      Integrable (fun ω => Real.exp (lam * gaussianWalk t ω))
        (gaussianProductMeasure σ) := by
  intro t lam; induction' t with t ih generalizing lam; simp_all +decide [ gaussianWalk ] ;
  -- The two factors are independent under the product measure.
  have h_indep : iIndepFun (fun i ω => ω i) (gaussianProductMeasure σ) :=
    gaussianProductMeasure_iIndepFun σ;
  have h_indep : IndepFun (fun ω => gaussianWalk t ω) (fun ω => ω t) (gaussianProductMeasure σ) := by
    simp +decide [ gaussianWalk ];
    convert h_indep.indepFun_finset_sum_of_notMem _ _ using 1;
    rotate_left;
    fun_prop;
    exacts [ Finset.range t, by simp +decide, by ext; simp +decide [ Finset.sum_apply ] ];
  have h_indep : IndepFun (fun ω => Real.exp (lam * gaussianWalk t ω)) (fun ω => Real.exp (lam * ω t)) (gaussianProductMeasure σ) := by
    exact h_indep.comp ( Measurable.exp ( measurable_const.mul measurable_id' ) ) ( Measurable.exp ( measurable_const.mul measurable_id' ) );
  convert h_indep.integrable_mul ( ih lam ) ( coord_integrable_exp σ t lam ) using 1;
  ext ω; simp +decide [ gaussianWalk, Finset.sum_range_succ ] ; rw [ ← Real.exp_add ] ; ring_nf;

/-- The marginal MGF of coordinate `t` under `gaussianProductMeasure σ`. -/
lemma coord_mgf_val (σ : ℝ) (t : ℕ) (s : ℝ) :
    ∫ ω : ℕ → ℝ, Real.exp (s * ω t) ∂gaussianProductMeasure σ =
    Real.exp (↑(Real.toNNReal (σ ^ 2)) * s ^ 2 / 2) := by
  have h1 : ∫ ω : ℕ → ℝ, Real.exp (s * ω t) ∂gaussianProductMeasure σ =
    ∫ x : ℝ, Real.exp (s * x) ∂(gaussianProductMeasure σ).map (fun ω : ℕ → ℝ => ω t) := by
    rw [integral_map (measurable_pi_apply t).aemeasurable]
    exact Continuous.aestronglyMeasurable (by continuity)
  rw [h1, gaussianProductMeasure_map_coord]
  have h2 := congr_fun (@mgf_id_gaussianReal 0 (Real.toNNReal (σ ^ 2))) s
  simp [mgf] at h2; rw [h2]
  simp [Real.coe_toNNReal _ (sq_nonneg σ)]
  left; exact sq_nonneg σ

/-- For each fixed `s`, the conditional MGF of `ω_t` given `canonicalFiltration t`
equals the unconditional MGF value `exp(σ²s²/2)`, a.e. w.r.t. the trimmed measure. -/
lemma condExpKernel_mgf_coord_eq (σ : ℝ) (t : ℕ) (s : ℝ) :
    (fun (ω' : ℕ → ℝ) => mgf (fun (ω : ℕ → ℝ) => ω t)
      ((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω') s)
    =ᵐ[(gaussianProductMeasure σ).trim (canonicalFiltration.le t)]
    fun _ => Real.exp (↑(Real.toNNReal (σ ^ 2)) * s ^ 2 / 2) := by
  -- Step 1: conditional expectation = unconditional by independence
  have hm1_le : MeasurableSpace.comap (fun ω : ℕ → ℝ => ω t) (borel ℝ) ≤
      canonicalMeasurableSpace := (measurable_pi_apply t).comap_le
  have hSM : StronglyMeasurable[MeasurableSpace.comap (fun ω : ℕ → ℝ => ω t) (borel ℝ)]
      (fun ω : ℕ → ℝ => Real.exp (s * ω t)) := by
    apply Continuous.comp_stronglyMeasurable (by fun_prop)
    exact (continuous_const.mul continuous_id).stronglyMeasurable.comp_measurable
      (Measurable.of_comap_le le_rfl)
  have h_indep_condExp :
      (gaussianProductMeasure σ)[fun ω : ℕ → ℝ => Real.exp (s * ω t) | canonicalFiltration t]
      =ᵐ[gaussianProductMeasure σ]
      fun _ => ∫ ω : ℕ → ℝ, Real.exp (s * ω t) ∂gaussianProductMeasure σ :=
    condExp_indep_eq hm1_le (canonicalFiltration.le t) hSM (coord_indep_filtration σ t)
  -- Step 2: plug in coord_mgf_val
  rw [coord_mgf_val] at h_indep_condExp
  -- Step 3: convert from ae-μ to ae-μ.trim
  have h_trim : (gaussianProductMeasure σ)[fun ω : ℕ → ℝ => Real.exp (s * ω t) | canonicalFiltration t]
      =ᵐ[(gaussianProductMeasure σ).trim (canonicalFiltration.le t)]
      fun _ => Real.exp (↑(Real.toNNReal (σ ^ 2)) * s ^ 2 / 2) := by
    rwa [StronglyMeasurable.ae_eq_trim_iff (canonicalFiltration.le t)
      stronglyMeasurable_condExp stronglyMeasurable_const]
  -- Step 4: relate condExp to kernel integral via condExp_ae_eq_trim_integral_condExpKernel
  have h_kernel := condExp_ae_eq_trim_integral_condExpKernel
    (canonicalFiltration.le t) (coord_integrable_exp σ t s)
  -- Step 5: combine: kernel integral =ᵐ condExp =ᵐ exp(...)
  filter_upwards [h_trim, h_kernel] with ω' h1 h2
  simp only [mgf]
  linarith

/-
Hypothesis 4: the increment `gaussianWalk (t+1) - gaussianWalk t
= ω_t` has a conditional sub-Gaussian MGF bound with parameter `σ²`
given `canonicalFiltration t`.
-/
lemma gaussianWalk_increments_subG (σ : ℝ) (hσ : 0 < σ) :
    ∀ t : ℕ,
      HasCondSubgaussianMGF (canonicalFiltration t)
        (canonicalFiltration.le t)
        (fun ω => gaussianWalk (t + 1) ω - gaussianWalk t ω)
        (Real.toNNReal (σ ^ 2)) (gaussianProductMeasure σ) := by
  intro t
  have heq : (fun ω : ℕ → ℝ => gaussianWalk (t + 1) ω - gaussianWalk t ω) =
    (fun ω => ω t) := funext (gaussianWalk_increment t)
  rw [heq]
  unfold HasCondSubgaussianMGF
  constructor
  · -- integrable_exp_mul: ∀ s, Integrable (fun ω => exp(s * ω t)) (κ ∘ₘ ν)
    intro s
    rw [condExpKernel_comp_trim]
    exact coord_integrable_exp σ t s
  · -- Step 1: ae equality at each rational
    have h_ae_all_rat : ∀ᵐ (ω' : ℕ → ℝ) ∂(gaussianProductMeasure σ).trim (canonicalFiltration.le t),
        ∀ q : ℚ, mgf (fun (ω : ℕ → ℝ) => ω t)
          ((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω') (q : ℝ)
        = Real.exp (↑(Real.toNNReal (σ ^ 2)) * (q : ℝ) ^ 2 / 2) := by
      rw [eventually_countable_forall]
      intro q
      exact condExpKernel_mgf_coord_eq σ t (q : ℝ)
    -- Step 2: extend from ℚ to ℝ via density + continuity
    filter_upwards [h_ae_all_rat] with ω' h_rat
    intro s
    -- By the continuity of the exponential function and the fact that the mgf is log-convex, we can extend the equality from rationals to reals.
    have h_cont : ∀ s : ℝ, mgf (fun ω => ω t) ((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω') s ≤ Real.exp (↑(σ ^ 2).toNNReal * s ^ 2 / 2) := by
      intro s
      have h_seq : ∃ seq : ℕ → ℚ, Filter.Tendsto (fun n => (seq n : ℝ)) Filter.atTop (nhds s) := by
        exact ⟨ fun n => Classical.choose ( exists_rat_btwn ( show s - 1 / ( n + 1 ) < s by simp +decide ; positivity ) ), by exact tendsto_iff_dist_tendsto_zero.mpr <| squeeze_zero ( fun _ => by positivity ) ( fun n => by simpa using abs_sub_le_iff.mpr ⟨ by linarith [ Classical.choose_spec ( exists_rat_btwn <| sub_lt_self s <| inv_pos.mpr <| Nat.cast_add_one_pos n ) ], by linarith [ Classical.choose_spec ( exists_rat_btwn <| sub_lt_self s <| inv_pos.mpr <| Nat.cast_add_one_pos n ) ] ⟩ ) <| tendsto_one_div_add_atTop_nhds_zero_nat ⟩
      obtain ⟨ seq, hseq ⟩ := h_seq;
      have h_liminf : ∫⁻ ω, ENNReal.ofReal (Real.exp (s * ω t)) ∂((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω') ≤ Filter.liminf (fun n => ∫⁻ ω, ENNReal.ofReal (Real.exp ((seq n : ℝ) * ω t)) ∂((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω')) Filter.atTop := by
        refine' le_trans _ ( MeasureTheory.lintegral_liminf_le _ );
        · refine' MeasureTheory.lintegral_mono fun ω => _;
          rw [ Filter.Tendsto.liminf_eq ];
          exact ENNReal.tendsto_ofReal ( Real.continuous_exp.continuousAt.tendsto.comp ( hseq.mul_const _ ) );
        · fun_prop;
      have h_liminf_eq : Filter.liminf (fun n => ∫⁻ ω, ENNReal.ofReal (Real.exp ((seq n : ℝ) * ω t)) ∂((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω')) Filter.atTop = ENNReal.ofReal (Real.exp (↑(σ ^ 2).toNNReal * s ^ 2 / 2)) := by
        have h_liminf_eq : ∀ n, ∫⁻ ω, ENNReal.ofReal (Real.exp ((seq n : ℝ) * ω t)) ∂((condExpKernel (gaussianProductMeasure σ) (canonicalFiltration t)) ω') = ENNReal.ofReal (Real.exp (↑(σ ^ 2).toNNReal * (seq n : ℝ) ^ 2 / 2)) := by
          intro n; specialize h_rat ( seq n ) ; simp_all +decide [ mgf ] ;
          rw [ ← h_rat, MeasureTheory.ofReal_integral_eq_lintegral_ofReal ];
          · exact ( by contrapose! h_rat; rw [ MeasureTheory.integral_undef h_rat ] ; positivity );
          · exact Filter.Eventually.of_forall fun x => Real.exp_nonneg _;
        rw [ Filter.liminf_congr ( Filter.Eventually.of_forall h_liminf_eq ) ];
        exact Filter.Tendsto.liminf_eq ( by exact ENNReal.tendsto_ofReal ( by exact Filter.Tendsto.rexp ( by exact Filter.Tendsto.div_const ( tendsto_const_nhds.mul ( hseq.pow 2 ) ) _ ) ) );
      convert ENNReal.toReal_mono _ h_liminf using 1;
      · unfold mgf;
        rw [ MeasureTheory.integral_eq_lintegral_of_nonneg_ae ];
        · exact Filter.Eventually.of_forall fun ω => Real.exp_nonneg _;
        · exact Measurable.aestronglyMeasurable ( by exact Measurable.exp ( measurable_const.mul ( measurable_pi_apply t ) ) );
      · rw [ h_liminf_eq, ENNReal.toReal_ofReal ( Real.exp_nonneg _ ) ];
      · aesop;
    exact h_cont s

/-- Hypothesis 5: the conditional mean of the increment `ω_t` given
`canonicalFiltration t` is zero. -/
lemma gaussianWalk_increments_zero_mean (σ : ℝ) :
    ∀ t,
      (gaussianProductMeasure σ)[
        fun ω => gaussianWalk (t + 1) ω - gaussianWalk t ω
        | canonicalFiltration t] =ᵐ[gaussianProductMeasure σ] 0 := by
  intro t
  have heq : (fun ω : ℕ → ℝ => gaussianWalk (t + 1) ω - gaussianWalk t ω) =
      (fun ω => ω t) := funext (gaussianWalk_increment t)
  rw [heq]
  have hm1_le : MeasurableSpace.comap (fun ω : ℕ → ℝ => ω t) (borel ℝ) ≤
      canonicalMeasurableSpace := (measurable_pi_apply t).comap_le
  have hSM : StronglyMeasurable[MeasurableSpace.comap (fun ω : ℕ → ℝ => ω t) (borel ℝ)]
      (fun ω : ℕ → ℝ => ω t) :=
    (measurable_id.stronglyMeasurable).comp_measurable (Measurable.of_comap_le le_rfl)
  have hstep := condExp_indep_eq hm1_le (canonicalFiltration.le t) hSM
    (coord_indep_filtration σ t)
  rw [coord_integral_zero] at hstep
  exact hstep

/-! ## Standard Borel space instance on `ℕ → ℝ` -/

noncomputable instance : @StandardBorelSpace (ℕ → ℝ) canonicalMeasurableSpace := by
  infer_instance

/-! ## Strengthened sharpness witness -/

/-- The iid-standard-Gaussian random walk realises the Pythia
`SubGaussianMG` structure with parameter `σ`, and the structure's
`process` field is `gaussianWalk`. -/
theorem gaussianWalk_isSubGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    ∃ M : SubGaussianMG σ canonicalFiltration
            (gaussianProductMeasure σ),
      M.process = gaussianWalk :=
  Pythia.one_d_marginal_reduction_tight hσ gaussianWalk
    gaussianWalk_adapted
    (gaussianWalk_integrable σ)
    (gaussianWalk_increments_subG σ hσ)
    (gaussianWalk_integrable_exp σ)
    (gaussianWalk_increments_zero_mean σ)

/-- Legacy weak Nonempty form. -/
theorem gaussianWalk_subGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    Nonempty (SubGaussianMG σ canonicalFiltration
      (gaussianProductMeasure σ)) :=
  ⟨(gaussianWalk_isSubGaussianMG σ hσ).choose⟩

end Pythia