/-
Kairos.Stats.GaussianRandomWalk — crossing-probability scaffold
for sub-Gaussian random walks.

Downstream of `Kairos.Stats.GaussianSmallBall`:
the `gaussian_small_ball_lower_bound` lemma gives the per-step
anti-concentration that supports a boundary-hugging Gaussian-walk
adversary.  Here we build the random-walk object itself: a sum of
iid standard Gaussian increments on `ℝ^ℕ` with the canonical product
measure and canonical filtration.

Target lemmas (all scaffolded with sorries, Aristotle closes):
- `gaussianWalk_subGaussianMG`: the iid-Gaussian random walk is a
  `SubGaussianMG σ 𝓕 μ`.
- `gaussianWalk_crossing_prob_lower`: for a strictly-increasing
  threshold `c(t)`, the probability of crossing `c(t)` at time `t`
  is bounded below by a quantity involving the small-ball constant
  from `GaussianSmallBall`.
-/

import Mathlib
import Kairos.Stats.Basic
import Kairos.Stats.GaussianSmallBall
import Kairos.Stats.SubGaussianMG

namespace Kairos.Stats

open MeasureTheory ProbabilityTheory

/-- The canonical MeasurableSpace on `ℕ → ℝ`: the product sigma-
algebra from the per-coordinate Borel sigma-algebra on `ℝ`. Named
for downstream reuse in `canonicalFiltration` + `gaussianWalk`. -/
instance canonicalMeasurableSpace : MeasurableSpace (ℕ → ℝ) :=
  MeasurableSpace.pi

/-- The product measure `μ_ℝℕ = ⨂_{n ∈ ℕ} gaussianReal 0 σ²` on
`ℝ^ℕ`: the canonical iid-standard-Gaussian-increment space.
Stated as `sorry` at the measure level; downstream consumers treat
it as abstract. Explicit construction requires the
`IsProbabilityMeasure` instance on each per-coordinate factor and
a `pi`-extension of it, both of which live behind Mathlib helpers
that are not yet fully unfolded in this scaffold. -/
noncomputable def gaussianProductMeasure (_σ : ℝ) :
    @Measure (ℕ → ℝ) canonicalMeasurableSpace := by
  sorry

/-- Scaffold-level `IsFiniteMeasure` on the sorry'd product measure. The
canonical Gaussian product IS a probability measure (hence finite); the
instance is stated sorry-axiomatic because the definition itself is sorry,
and downstream callers require it in scope to invoke `SubGaussianMG`. -/
noncomputable instance (σ : ℝ) :
    IsFiniteMeasure (gaussianProductMeasure σ) := by sorry

/-- The canonical filtration on `ℝ^ℕ`: `𝓕_n` is the σ-algebra
generated by the first `n` coordinate projections.  Adapted
processes are those whose `t`-th coordinate depends only on the
first `t` increments. -/
noncomputable def canonicalFiltration :
    Filtration ℕ canonicalMeasurableSpace := by
  sorry

/-- The Gaussian random walk: `M_t ω = Σ_{i < t} ω i`.  On the
canonical-filtration / gaussian-product measure space this is a
`SubGaussianMG` instance. -/
noncomputable def gaussianWalk (t : ℕ) (ω : ℕ → ℝ) : ℝ :=
  (Finset.range t).sum (fun i => ω i)

/-- The iid-standard-Gaussian random walk realises our
`SubGaussianMG` structure with parameter `σ`.  This provides the
explicit non-vacuous witness that the deployment-slack theorems
quantify over. -/
theorem gaussianWalk_subGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    Nonempty (SubGaussianMG σ canonicalFiltration
      (gaussianProductMeasure σ)) := by
  sorry

end Kairos.Stats
