/-
Pythia.GaussianRandomWalk — crossing-probability scaffold
for sub-Gaussian random walks.

Downstream of `Pythia.GaussianSmallBall`:
the `gaussian_small_ball_lower_bound` lemma gives the per-step
anti-concentration that supports a boundary-hugging Gaussian-walk
adversary.  Here we build the random-walk object itself: a sum of
iid standard Gaussian increments on `ℝ^ℕ` with the canonical product
measure and canonical filtration.

Target lemmas:

* `gaussianProductMeasure` (closed): `Measure.infinitePiNat` over
  per-coordinate `gaussianReal 0 σ²`. From Aristotle project
  `9156a0fd` (2026-04-28), partial closure.
* `IsFiniteMeasure (gaussianProductMeasure σ)` instance (closed):
  inferred from `Measure.infinitePiNat`'s automatic instance.
* `canonicalFiltration` (closed): `iSup`-of-comap construction,
  generated by the first `n+1` coordinate projections.
* `gaussianWalk_isSubGaussianMG` (open, decomposed below): the
  iid-Gaussian random walk `M_t = Σ_{i<t} ω_i` realises the Pythia
  `SubGaussianMG` structure with parameter σ, with the structure's
  process field pinned to `gaussianWalk` (no degenerate constant
  / zero-process witnesses can inhabit this type).

The proof factors through `Pythia.one_d_marginal_reduction_tight`
(in `Pythia.VectorSharpness`), which turns five hypotheses on a
process M into `∃ M' : SubGaussianMG σ 𝓕 μ, M'.process = M`. Each
of the five sub-targets below is a named sorry to make the
decomposition visible in `lake build` warnings + `#print axioms`.
-/

import Mathlib
import Pythia.Basic
import Pythia.GaussianSmallBall
import Pythia.SubGaussianMG
import Pythia.VectorSharpness

namespace Pythia

open MeasureTheory ProbabilityTheory

/-- The canonical MeasurableSpace on `ℕ → ℝ`: the product sigma-
algebra from the per-coordinate Borel sigma-algebra on `ℝ`. Named
for downstream reuse in `canonicalFiltration` + `gaussianWalk`. -/
instance canonicalMeasurableSpace : MeasurableSpace (ℕ → ℝ) :=
  MeasurableSpace.pi

/-- The product measure `μ_ℝℕ = ⨂_{n ∈ ℕ} gaussianReal 0 σ²` on
`ℝ^ℕ`: the canonical iid-standard-Gaussian-increment space. -/
noncomputable def gaussianProductMeasure (σ : ℝ) :
    @Measure (ℕ → ℝ) canonicalMeasurableSpace :=
  Measure.infinitePiNat (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2)))

/-- The Gaussian product measure is a finite measure (in fact a
probability measure). -/
noncomputable instance (σ : ℝ) :
    IsFiniteMeasure (gaussianProductMeasure σ) := by
  unfold gaussianProductMeasure
  exact inferInstanceAs (IsFiniteMeasure (Measure.infinitePiNat _))

/-- The canonical filtration on `ℝ^ℕ`: `𝓕_n` is the σ-algebra
generated by the first `n+1` coordinate projections.  Adapted
processes are those whose `t`-th coordinate depends only on the
first `t` increments. -/
noncomputable def canonicalFiltration :
    Filtration ℕ canonicalMeasurableSpace where
  seq n := ⨆ (j : ℕ) (_ : j ≤ n),
    MeasurableSpace.comap (fun (ω : ℕ → ℝ) => ω j) (borel ℝ)
  mono' i j hij :=
    iSup_mono fun k => iSup_mono' fun hk => ⟨le_trans hk hij, le_rfl⟩
  le' n := iSup_le fun j => iSup_le fun _ => (measurable_pi_apply j).comap_le

/-- The Gaussian random walk: `M_t ω = Σ_{i < t} ω i`.  On the
canonical-filtration / gaussian-product measure space this is a
`SubGaussianMG` instance. -/
noncomputable def gaussianWalk (t : ℕ) (ω : ℕ → ℝ) : ℝ :=
  (Finset.range t).sum (fun i => ω i)

/-! ## SubGaussianMG hypothesis-helpers for `gaussianWalk` (open)

The five hypotheses needed by `Pythia.one_d_marginal_reduction_tight`
to construct the SubGaussianMG record. Each is a named sorry —
visible in the `lake build` warning surface, individually targetable
by Aristotle / Sonnet drafters / pythia tactic ladder.
-/

/-- Hypothesis 1: the gaussian random walk is adapted to
`canonicalFiltration`. `gaussianWalk t = Σ_{i<t} ω_i` depends only
on the first `t` coordinates, all of which are
`canonicalFiltration t`-measurable by construction (the filtration
is the σ-algebra of the first `n+1` coordinate projections). -/
lemma gaussianWalk_adapted :
    Adapted canonicalFiltration gaussianWalk := by
  sorry

/-- Hypothesis 2: each `gaussianWalk t` is integrable under the
Gaussian product measure. Each coordinate `ω i` is integrable as
the marginal `gaussianReal 0 σ²` under `Measure.infinitePiNat`, and
the finite sum of integrable functions is integrable. -/
lemma gaussianWalk_integrable (σ : ℝ) :
    ∀ t, Integrable (gaussianWalk t) (gaussianProductMeasure σ) := by
  sorry

/-- Hypothesis 3: each `Real.exp (lam * gaussianWalk t)` is
integrable for every `lam : ℝ`. Under independence (product
measure), `exp(lam · Σ ω_i) = Π exp(lam · ω_i)`, and each factor
has finite Gaussian MGF `exp(lam²σ²/2)`. -/
lemma gaussianWalk_integrable_exp (σ : ℝ) :
    ∀ t : ℕ, ∀ lam : ℝ,
      Integrable (fun ω => Real.exp (lam * gaussianWalk t ω))
        (gaussianProductMeasure σ) := by
  sorry

/-- Hypothesis 4: the increment `gaussianWalk (t+1) - gaussianWalk t
= ω_t` has a conditional sub-Gaussian MGF bound with parameter `σ²`
given `canonicalFiltration t`. Under `Measure.infinitePiNat`, the
t-th coordinate is independent of the first `t` coordinates (which
generate `canonicalFiltration t`), so the conditional MGF given
`𝓕_t` equals the unconditional Gaussian MGF, which is
`exp(σ²·lam²/2)` exactly — saturates the sub-Gaussian bound. -/
lemma gaussianWalk_increments_subG (σ : ℝ) (hσ : 0 < σ) :
    ∀ t : ℕ,
      HasCondSubgaussianMGF (canonicalFiltration t)
        (canonicalFiltration.le t)
        (fun ω => gaussianWalk (t + 1) ω - gaussianWalk t ω)
        (Real.toNNReal (σ ^ 2)) (gaussianProductMeasure σ) := by
  sorry

/-- Hypothesis 5: the conditional mean of the increment `ω_t` given
`canonicalFiltration t` is zero. Same independence argument as in
hypothesis 4: the marginal of `ω_t` under `gaussianReal 0 σ²` has
mean zero, and conditioning on the first `t` coordinates leaves
the marginal unchanged. -/
lemma gaussianWalk_increments_zero_mean (σ : ℝ) :
    ∀ t,
      (gaussianProductMeasure σ)[
        fun ω => gaussianWalk (t + 1) ω - gaussianWalk t ω
        | canonicalFiltration t] =ᵐ[gaussianProductMeasure σ] 0 := by
  sorry

/-! ## Standard Borel space instance on `ℕ → ℝ`

Required by `SubGaussianMG`'s `[StandardBorelSpace Ω]` constraint
(propagated from `HasCondSubgaussianMGF`'s `condExpKernel`
machinery). The countable product of standard Borel spaces is
itself standard Borel.
-/

/-- Standard Borel structure on `(ℕ → ℝ)`. Mathlib v4.28 provides
this via `Pi.standardBorelSpace` for countable index types over
standard Borel factors; pinned here as an instance for downstream
SubGaussianMG construction. -/
noncomputable instance : @StandardBorelSpace (ℕ → ℝ) canonicalMeasurableSpace := by
  sorry

/-! ## Strengthened sharpness witness

The non-degenerate-witness form of the matching-lower-bound
adversary: an explicit `SubGaussianMG` whose process is
`gaussianWalk` (not any inhabitant). Constructed by feeding the
five hypotheses above into `Pythia.one_d_marginal_reduction_tight`.

If any of the five hypothesis-helpers above is closed, this
theorem becomes correspondingly more axiom-clean. The current
sorry resolves to the conjunction of the five named sorries,
making per-helper progress visible.
-/

/-- The iid-standard-Gaussian random walk realises the Pythia
`SubGaussianMG` structure with parameter `σ`, and the structure's
`process` field is `gaussianWalk` (forbidding the constant /
zero-process degenerate inhabitants the `Nonempty` form admits). -/
theorem gaussianWalk_isSubGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    ∃ M : SubGaussianMG σ canonicalFiltration
            (gaussianProductMeasure σ),
      M.process = gaussianWalk :=
  Pythia.one_d_marginal_reduction_tight hσ gaussianWalk
    gaussianWalk_adapted
    (gaussianWalk_integrable σ)
    (gaussianWalk_increments_subG σ hσ)
    (gaussianWalk_integrable_exp σ)
    (gaussianWalk_increments_zero_mean σ)

/-- Legacy weak Nonempty form. Kept for backward-compat with
existing downstream callers; consumers should switch to
`gaussianWalk_isSubGaussianMG`. -/
theorem gaussianWalk_subGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    Nonempty (SubGaussianMG σ canonicalFiltration
      (gaussianProductMeasure σ)) :=
  ⟨(gaussianWalk_isSubGaussianMG σ hσ).choose⟩

end Pythia
