/-
Pythia.GaussianRandomWalk — crossing-probability scaffold
for sub-Gaussian random walks.

Downstream of `Pythia.GaussianSmallBall`:
the `gaussian_small_ball_lower_bound` lemma gives the per-step
anti-concentration that supports a boundary-hugging Gaussian-walk
adversary.  Here we build the random-walk object itself: a sum of
iid standard Gaussian increments on `ℝ^ℕ` with the canonical product
measure and canonical filtration.

Target lemmas:

* `gaussianProductMeasure` (closed): `Measure.infinitePiNat` over
  per-coordinate `gaussianReal 0 σ²`. From Aristotle project
  `9156a0fd` (2026-04-28), partial closure.
* `IsFiniteMeasure (gaussianProductMeasure σ)` instance (closed):
  inferred from `Measure.infinitePiNat`'s automatic instance.
* `canonicalFiltration` (closed): `iSup`-of-comap construction,
  generated by the first `n+1` coordinate projections.
* `gaussianWalk_subGaussianMG` (open, see comment below): requires
  the witness to BE `gaussianWalk` (not just any inhabitant), so
  `Nonempty (...)` is too weak a target.  Tracked as a non-trivial
  proof obligation; the existing partial-Aristotle witness uses a
  constant adapted process which trivially satisfies the structure
  fields but does not realise the Gaussian random walk we need for
  the matching lower bound.  Carried as a flagged sorry per the
  honest-scaffold rule.
-/

import Mathlib
import Pythia.Basic
import Pythia.GaussianSmallBall
import Pythia.SubGaussianMG

namespace Pythia

open MeasureTheory ProbabilityTheory

/-- The canonical MeasurableSpace on `ℕ → ℝ`: the product sigma-
algebra from the per-coordinate Borel sigma-algebra on `ℝ`. Named
for downstream reuse in `canonicalFiltration` + `gaussianWalk`. -/
instance canonicalMeasurableSpace : MeasurableSpace (ℕ → ℝ) :=
  MeasurableSpace.pi

/-- The product measure `μ_ℝℕ = ⨂_{n ∈ ℕ} gaussianReal 0 σ²` on
`ℝ^ℕ`: the canonical iid-standard-Gaussian-increment space. -/
noncomputable def gaussianProductMeasure (σ : ℝ) :
    @Measure (ℕ → ℝ) canonicalMeasurableSpace :=
  Measure.infinitePiNat (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2)))

/-- The Gaussian product measure is a finite measure (in fact a
probability measure). -/
noncomputable instance (σ : ℝ) :
    IsFiniteMeasure (gaussianProductMeasure σ) := by
  unfold gaussianProductMeasure
  exact inferInstanceAs (IsFiniteMeasure (Measure.infinitePiNat _))

/-- The canonical filtration on `ℝ^ℕ`: `𝓕_n` is the σ-algebra
generated by the first `n+1` coordinate projections.  Adapted
processes are those whose `t`-th coordinate depends only on the
first `t` increments. -/
noncomputable def canonicalFiltration :
    Filtration ℕ canonicalMeasurableSpace where
  seq n := ⨆ (j : ℕ) (_ : j ≤ n),
    MeasurableSpace.comap (fun (ω : ℕ → ℝ) => ω j) (borel ℝ)
  mono' i j hij :=
    iSup_mono fun k => iSup_mono' fun hk => ⟨le_trans hk hij, le_rfl⟩
  le' n := iSup_le fun j => iSup_le fun _ => (measurable_pi_apply j).comap_le

/-- The Gaussian random walk: `M_t ω = Σ_{i < t} ω i`.  On the
canonical-filtration / gaussian-product measure space this is a
`SubGaussianMG` instance. -/
noncomputable def gaussianWalk (t : ℕ) (ω : ℕ → ℝ) : ℝ :=
  (Finset.range t).sum (fun i => ω i)

/-- The iid-standard-Gaussian random walk realises our
`SubGaussianMG` structure with parameter `σ`.  This provides the
explicit non-vacuous witness that the deployment-slack theorems
quantify over.

The `Nonempty (...)` form below is the legacy weak target;
Aristotle attempts (`9156a0fd`, `b505d132`, 2026-04-28) closed it
with degenerate constant / zero-process witnesses, which satisfy
the existential vacuously and do not realise the Gaussian random
walk the matching lower bound quantifies over. Kept as a flagged
sorry; the strengthened theorem
`gaussianWalk_isSubGaussianMG` below is what consumers should use. -/
theorem gaussianWalk_subGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    Nonempty (SubGaussianMG σ canonicalFiltration
      (gaussianProductMeasure σ)) := by
  sorry

/-- **Strengthened sharpness witness** — the explicit Gaussian
random walk `M_t ω = Σ_{i<t} ω_i` is a sub-Gaussian martingale on
the canonical Gaussian-product space. This is the
non-degenerate-witness form the matching lower bound requires:
the structure's `process` field is pinned to `gaussianWalk`, so
no constant or zero process can inhabit the type.

Aristotle target. The proof requires:
  * adapted: `Finset.range t .sum (fun i => ω i)` is
    `canonicalFiltration t`-measurable (depends only on the first
    `t` coordinates).
  * integrable: each `gaussianWalk t` is integrable under
    `gaussianProductMeasure σ` (finite sum of integrable Gaussians).
  * integrable_exp: `Real.exp (lam * gaussianWalk t)` is integrable
    for all `lam : ℝ` (Gaussian MGF is finite everywhere).
  * increments_subG: the increment `M_{t+1} - M_t = ω_t` has
    conditional sub-Gaussian MGF bound with parameter `σ²`,
    conditioned on `𝓕_t`. Standard sub-Gaussian bound applied
    coordinate-wise under independence (product measure).
  * increments_zero_mean: the conditional mean of `ω_t` given
    `𝓕_t` is zero. Standard fact under product of zero-mean
    factors. -/
theorem gaussianWalk_isSubGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    ∃ M : SubGaussianMG σ canonicalFiltration
            (gaussianProductMeasure σ),
      M.process = gaussianWalk := by
  sorry

end Pythia
